### ISSUE TITLE
Issue with PSF license

### ISSUE THREAD

**Issue by pganssle** [Zac-HD/stdlib-property-tests#9]
So I noticed today that this is licensed under the PSF license and under MPL, but weirdly enough CPython cannot accept code licensed under the PSF because the PSF license is not compatible with itself. [The wiki suggests that you not use the PSF license](https://wiki.python.org/moin/PythonSoftwareFoundationLicenseFaq#How_do_I_use_the_PSF_License.3F), and that for things that might get contributed to the standard library, use another permissive license like Apache 2.0.

Right now it's just me, @Zac-HD and @cfbolz who have contributed to this repository, so I think it's early enough that re-licensing the old commits won't be a big deal, but we should probably convert the permissive license over to Apache 2.0 unless the time horizon for "move this into the standard library" is short enough that we're not likely to get new contributors and none of us is going to disappear (in which case re-licensing to "contributed under the CLA" seems equivalent to re-licensing to Apache).

I only noticed this because when I was writing `zoneinfo` I tried to figure out how to apply the PSF license and saw this note, so I went with Apache 2.0 (and actually I have not been accepting contributions there because I wanted to figure out how to set things up to use the CLA if possible).

**Comment by Zac-HD** [comment]
Wow, thanks for pointing that out!  I'm certainly happy to switch PSFL for Apache 2.0, so we can do that as soon as @cfbolz agrees.

(which will result in dual MLP-or-Apache licence and everyone should be happy)

**Comment by cfbolz** [comment]
Oops, sorry for the delay! Yes, I am certainly happy to relicense.
